extends:
- ../bitir.yml
- ../fault_models.yml
- ../machines/frontier.yml
methodology:
  default_campaign: template
  float_abs_tol: 1e-5
  float_rel_tol: 0.0
run:
  machine: frontier
  benchmark_set: hecbench
  campaign: template
  fault_model: quick_float_8
  execution_mode: write-script
campaigns:
  template:
    benchmarks:
    - layout
benchmarks:
  layout:
    compare_mode: exact
    golden_file: layout.bin
    args:
    - '{LAYOUT_REPEAT}'
    env:
      LAYOUT_REPEAT: '1'
    source_dirs:
      hip: src/layout-hip
