extends: ../bitir.yml

machines:
  nvidia:
    build_dir: HeCBench/build-cuda118-smoke
    jobs:
      build:
        account: UIC-HPC
        queue: debug
        select: 1:ncpus=8:ngpus=1:mem=32gb
        filesystems: home:eagle
        walltime: 01:00:00
        stdout: OUT_golden_smoke.out
        stderr: ERROR_golden_smoke.err

run:
  machine: nvidia
  task: build
  campaign: smoke
  execution_mode: submit
